services:
  mcp_grareco:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp_grareco
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - PORT=${PORT:-3000}
      - HOST=${HOST:-0.0.0.0}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ANTHROPIC_MODEL=${ANTHROPIC_MODEL:-claude-3-sonnet-20240229}
      - ANTHROPIC_MAX_OUTPUT_TOKENS=${ANTHROPIC_MAX_OUTPUT_TOKENS:-8192}
      - ANTHROPIC_MAX_CONTEXT_WINDOW=${ANTHROPIC_MAX_CONTEXT_WINDOW:-200000}
      - ANTHROPIC_MAX_INPUT_TOKENS=${ANTHROPIC_MAX_INPUT_TOKENS:-50000}
      - GRARECO_OUTPUT_DIR=/app/output
      - NODE_ENV=production
    volumes:
      - ./output:/app/output
    restart: unless-stopped
